version: '2'
services:
  ms-rest-todos:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - 8080:8080
    container_name: ms-rest-todos
    external_links:
      - postgresdb:postgres
    networks:
      - default
      - postgresdb_default
networks:
  default:
  postgresdb_default:
    external: true

